#
# Unified Makefile for Handy/SDL Portable Lynx Emulator
#
# by James L. Hammons
#
# This software is licensed under the GPL v2 or any later version. Set the
# file GPL.TXT for details. ;-)
#

# NOTE: zlib is a dependency, but is not checked for.

# Figure out which system we're compiling for, and set the appropriate variables

HOST_OS := $(shell uname -s 2>/dev/null)

ifeq "$(OSTYPE)" "msys"							# Win32

SYSTYPE    = __GCCWIN32__
EXESUFFIX  = .exe
ICON       = obj/icon.o
MSG        = Win32 on MinGW

else
ifeq "$(HOST_OS)" "Darwin"

SYSTYPE    = __GCCUNIX__ -D_OSX_
EXESUFFIX  =
ICON       =
MSG        = Mac OS X

else											# *nix

SYSTYPE    = __GCCUNIX__
EXESUFFIX  =
ICON       =
MSG        = generic Unix/Linux

endif
endif

CC         = gcc
CXX        = g++
LD         = $(CXX)
TARGET     = handy_sdl

PKG_CONFIG ?= pkg-config
SDLCFLAGS  = $(shell $(PKG_CONFIG) --cflags sdl2 2>/dev/null)
SDLLIBS    = $(shell $(PKG_CONFIG) --libs sdl2 2>/dev/null)

# Note that we use optimization level 2 instead of 3--3 doesn't seem to gain much over 2
CFLAGS   = -MMD -Wall -Wno-switch -O2 -D$(SYSTYPE) -DANSI_GCC -DSDL_PATCH -ffast-math -fomit-frame-pointer $(SDLCFLAGS)
CPPFLAGS = -MMD -Wall -Wno-switch -Wno-non-virtual-dtor -O2 -D$(SYSTYPE) -DANSI_GCC -DSDL_PATCH \
		-ffast-math -fomit-frame-pointer $(SDLCFLAGS) -g

LDFLAGS =

LIBS = -L/usr/local/lib -L/usr/lib $(SDLLIBS) -lz -lm

INCS = -I./src -I./src/handy-0.95 -I/usr/local/include -I/usr/include

OBJS = \
		obj/cart.o \
		obj/memmap.o \
		obj/mikie.o \
		obj/ram.o \
		obj/rom.o \
		obj/susie.o \
		obj/system.o \
		obj/errorhandler.o \
		obj/unzip.o \
		obj/handy_sdl_main.o \
		obj/handy_sdl_handling.o \
		obj/handy_sdl_graphics.o \
		obj/handy_sdl_sound.o \
		obj/handy_sdl_comlynx.o \
		obj/handy_sdl_bootwatch.o \
		obj/handy_sdl_gui.o \
		obj/handy_sdl_config.o \
		obj/imgui.o \
		obj/imgui_draw.o \
		obj/imgui_tables.o \
		obj/imgui_widgets.o \
		obj/imgui_impl_sdl2.o \
		obj/imgui_impl_sdlrenderer2.o


all: checkenv message obj $(TARGET)$(EXESUFFIX)
	@echo
	@echo "*** Looks like it compiled OK... Give it a whirl!"

# Check the compilation environment, barf if not appropriate

checkenv:
	@echo
	@printf "*** Checking compilation environment... "
	@if ! command -v $(PKG_CONFIG) >/dev/null 2>&1; then \
		echo; \
		echo; \
		echo "It seems that you don't have pkg-config installed."; \
		echo "On Debian/Ubuntu: sudo apt install pkg-config"; \
		echo "On macOS with Homebrew: brew install pkg-config"; \
		echo; \
		exit 1; \
	fi
	@if ! $(PKG_CONFIG) --exists sdl2; then \
		echo; \
		echo; \
		echo "It seems that you don't have the SDL2 development libraries installed."; \
		echo "On Debian/Ubuntu: sudo apt install libsdl2-dev"; \
		echo "On macOS with Homebrew: brew install sdl2"; \
		echo; \
		exit 1; \
	fi
	@echo "OK"

message:
	@echo
	@echo "*** Building Handy/SDL for $(MSG)..."
	@echo

clean:
	@printf "*** Cleaning out the garbage..."
	@rm -rf obj
	@rm -f ./$(TARGET)$(EXESUFFIX)
	@echo done!

obj:
	@mkdir -p obj

# This is only done for Win32 at the moment...

#ifneq "" "$(ICON)"
#$(ICON): res/$(TARGET).rc res/$(TARGET).ico
#	@echo \*\*\* Processing icon...
#	@windres -i res/$(TARGET).rc -o $(ICON) --include-dir=./res
#endif

obj/%.o: src/handy-0.95/%.c
	@echo "*** Compiling $<..."
	@$(CC) $(CFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/handy-0.95/%.cpp
	@echo "*** Compiling $<..."
	@$(CXX) $(CPPFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/%.c
	@echo "*** Compiling $<..."
	@$(CC) $(CFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/%.cpp
	@echo "*** Compiling $<..."
	@$(CXX) $(CPPFLAGS) $(INCS) -c $< -o $@

# Vendored Dear ImGui. -w because it is third party and its warnings are not
# ours to fix; -fno-strict-aliasing to match upstream's build recommendations.
obj/%.o: src/imgui/%.cpp
	@echo "*** Compiling $<..."
	@$(CXX) $(CPPFLAGS) -w -fno-strict-aliasing $(INCS) -c $< -o $@

obj/%.o: src/zlib-113/%.c
	@echo "*** Compiling $<..."
	@$(CC) $(CFLAGS) $(INCS) -c $< -o $@
	
$(TARGET)$(EXESUFFIX): $(OBJS)
	@echo "*** Linking it all together..."
	@$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
#	strip --strip-all vj$(EXESUFFIX)
#	upx -9 vj$(EXESUFFIX)

# Pull in dependencies autogenerated by gcc's -MMD switch
# The "-" in front is there just in case they haven't been created yet

-include obj/*.d
