void handy_sdl_usage()
{
printf("Usage: ./handy_sdl romfile [options]\n");
printf("\n");
printf(" Global Handy/SDL options:\n");
printf("\n");
printf(" romfile              : Filename of the romfile. It can have several\n");
printf("                        extensions (.lnx/.o/.com/.bin). Gzipped and\n");
printf("                        zipped (.gz and .zip) are also supported.\n");
printf(" -frameskip 1 - 9     : Options to skip some frames. Default is 1.\n");
printf(" -[no]fullscreen      : Disable/Enable fullscreen rendering mode.\n");
printf(" -[no]throttle        : Disable/Enable throttle to a max of 60FPS.\n");
printf(" -[no]sound           : Disable/Enable sound support.\n");
printf(" -[no]autoskip        : Disable/Enable auto-frameskip\n");
printf(" -[no]fps             : Disable/Enable FPS counter in the title bar.\n");
printf("\n");
printf(" Display options:\n");
printf("\n");
printf(" -scale N             : Initial window size, N times the Lynx resolution\n");
printf(" -1 -2 -3 -4          : Shorthand for -scale 1 to 4. Default is 3.\n");
printf("                        The window is freely resizable afterwards; the\n");
printf("                        picture is scaled to fit with the aspect ratio\n");
printf("                        preserved.\n");
printf(" -[no]smooth          : Linear filtering when scaling up. Default is off,\n");
printf("                        which gives sharp, exact pixels.\n");
printf("\n");
printf(" ComLynx over TCP:\n");
printf("\n");
printf(" -comlynx listen:PORT       : Accept ComLynx peers on PORT\n");
printf(" -comlynx connect:HOST:PORT : Connect ComLynx to a listening peer\n");
printf("                              The link is a raw, unframed byte pipe:\n");
printf("                              whatever the cart sends on the Mikey UART\n");
printf("                              goes out the socket and vice versa. Use it\n");
printf("                              to link two emulators, to reach a real Lynx\n");
printf("                              over a bridge, or to attach any external\n");
printf("                              ComLynx device.\n");
printf(" -comlynxtrace              : Log every byte crossing the link\n");
printf("\n");
printf(" Keyboard controls:\n");
printf("\n");
printf(" Up/Down/Left/Right   : Lynx joypad\n");
printf(" Z                    : Lynx A\n");
printf(" X                    : Lynx B\n");
printf(" Return               : Lynx PAUSE\n");
printf(" F1                   : Lynx OPTION 1\n");
printf(" F2                   : Lynx OPTION 2\n");
printf(" Escape               : Power off and exit\n");
printf("\n");
printf(" The bindings are fixed; there is no joystick support yet.\n");

}
